# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qfluentwidgets import BodyLabel, CheckBox, CompactSpinBox, LineEdit, PrimaryPushButton

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 280, 521, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CheckBox_Mac = CheckBox(self.verticalLayoutWidget)
        self.CheckBox_Mac.setObjectName("CheckBox_Mac")
        self.horizontalLayout.addWidget(self.CheckBox_Mac)
        self.Edit_Mac = LineEdit(self.verticalLayoutWidget)
        self.Edit_Mac.setText("")
        self.Edit_Mac.setAlignment(QtCore.Qt.AlignCenter)
        self.Edit_Mac.setObjectName("Edit_Mac")
        self.horizontalLayout.addWidget(self.Edit_Mac)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.BodyLabel = BodyLabel(self.verticalLayoutWidget)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout.addWidget(self.BodyLabel)
        self.CompactSpinBox_MacOffset = CompactSpinBox(self.verticalLayoutWidget)
        self.CompactSpinBox_MacOffset.setObjectName("CompactSpinBox_MacOffset")
        self.horizontalLayout.addWidget(self.CompactSpinBox_MacOffset)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CheckBox_FirmUpdate = CheckBox(self.verticalLayoutWidget)
        self.CheckBox_FirmUpdate.setObjectName("CheckBox_FirmUpdate")
        self.horizontalLayout_2.addWidget(self.CheckBox_FirmUpdate)
        self.Edit_FirmVersion = LineEdit(self.verticalLayoutWidget)
        self.Edit_FirmVersion.setText("")
        self.Edit_FirmVersion.setAlignment(QtCore.Qt.AlignCenter)
        self.Edit_FirmVersion.setReadOnly(True)
        self.Edit_FirmVersion.setObjectName("Edit_FirmVersion")
        self.horizontalLayout_2.addWidget(self.Edit_FirmVersion)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.Button_FileSel = PrimaryPushButton(self.verticalLayoutWidget)
        self.Button_FileSel.setObjectName("Button_FileSel")
        self.horizontalLayout_2.addWidget(self.Button_FileSel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.CheckBox_Mac.setText(_translate("Dialog", "MAC写入"))
        self.Edit_Mac.setPlaceholderText(_translate("Dialog", "起始MAC地址"))
        self.BodyLabel.setText(_translate("Dialog", "递增"))
        self.CheckBox_FirmUpdate.setText(_translate("Dialog", "固件升级"))
        self.Edit_FirmVersion.setPlaceholderText(_translate("Dialog", "固件版本"))
        self.Button_FileSel.setText(_translate("Dialog", "选择"))

