#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1 

test() {
	sleep 23

        sn=`uci get 4g.server.sn`
        uci set test.server.sn=$sn

	. /lib/functions.sh
        config_load test
        uci commit test

        local start_num
        local hub_ok
        local hub_faile

        config_get hub_ok test hub_ok
        config_get hub_faile test hub_faile
        config_get start_num test start_num


        echo "-----read---->start_num:$start_num"
        echo "-----read---->hub_faile:$hub_faile"
        echo "-----read---->hub_ok:$hub_ok"

        let start_num+=1
        uci set test.test.start_num=$start_num

        Hub=`lsusb |grep "05e3:0620"|awk '{ print $6 }'`
        echo "--------->Hub_id:$Hub"

        if [ "05e3:0620"X == "$Hub"X ];then
                let hub_ok+=1
                uci set test.test.hub_ok=$hub_ok
        else
                let hub_faile+=1
                uci set test.test.hub_faile=$hub_faile
        fi

        echo "-----result---->start_num:$start_num"
        echo "-----result---->hub_faile:$hub_faile"
        echo "-----result---->hub_ok:$hub_ok"

        uci commit test
}


start_service() {
	test
}




